junobuild/docs

- docs/add-juno-to-an-app/create-a-satellite.md
- docs/add-juno-to-an-app/install-the-sdk-and-initialize-juno.md
- docs/intro.md
Couple of issues I spotted while reading the first pages of the getting started guide.
> docs: fix typos and links

- docusaurus.config.js
Maybe there's already a link but I couldn't find it. Close & edit at will.
> feat: console link on landing page

- docs/build/storage.md
Parameter for `deleteAsset` is also updated.
https://github.com/buildwithjuno/juno-js/pull/45
> docs: no timestamp check when deleting assets

- src/components/Hero/index.tsx
- src/components/Outro/index.tsx
- src/components/Start/index.tsx
- src/providers/analytics.providers.ts
I'm curious to see how the `trackEvent` feature would work if applied to external link and also interested to know if the call to action of the main page of the documentation are used.
> feat: track "Start building" and "Documentation" event

- docs/miscellaneous/memory.md
Reference: https://forum.dfinity.org/t/why-asset-canister-limit-1gb-instead-of-2gb/25532
> docs: memory heap max 1 GB instead of 2 GB

- docs/build/datastore.md
- docs/build/storage.md
Added the return type for `listAssets` and `listDocs`, which resolves issue #86. 
I have attached an image to ensure the format is correct.
The format is the same for `listAssets`.
> Added the return type for listAssets and listDocs

- docs/guides/local-development.md
Closes #136 
Mentioned the minimal version of Docker Desktop in the "Before You Begin" section of the "Local Development" in the documentation.
> docs: added minimal docker version on MacBook for local dev

- docs/guides/github-actions.md
- Updated GitHub Actions in the [GH actions - Guides and Examples](https://juno.build/docs/guides/github-actions):
- Bumped `actions/checkout@v3` to `actions/checkout@v4`.
- Bumped `actions/setup-node@v3` to `actions/setup-node@v4`.
Resolves https://github.com/junobuild/juno-action/issues/3
> docs: update GH action versions in the Guides & Examples

- showcase.json
Project THE REGISTRY seems to have been deprecated. https://theregistry.app leads to a 404.
> feat: remove THE REGISTRY from showcase (project is deprecated?)

- docs/roadmap.md
When I updated the roadmap in #163, I missed some copy / paste and therefore few entries were missing in the roadmap as provided in the white paper.
> docs: add missing entries to roadmap

- juno.config.ts
I think it makes sense to have a single PDF for the white paper, without hashed file names, otherwise I would always need to update backlinks. For traceability, the white paper is also available as HTML, and the commit history shows the same changes. Therefore, I'll redirect the PDFs I released yesterday—both the original and the one that fixed a typo.
> feat: redirects white papers v1.0.0 and v1.0.1

- src/components/Testimonial/index.tsx
- src/components/Testimonials/index.tsx
- src/components/Testimonials/styles.module.scss
Add Konstantin testimonial and change the semantic to a list
> feat: add Konstantin testimonial

- docs/guides/angular.md
- docs/guides/astro.md
- docs/guides/react.md
- docs/guides/sveltekit.md
- docs/guides/vue.md
Not really sure if that was intentional, but it feels like the correct name should be the one of the framework to which the documentation refers.
> docs: adjust frameworks names in guides

- docs/build/datastore.md
There was a typo / leftover. The Datastore now also use "stable" as default.
Resolves #192
> fix: default memory allocation for Datastore is stable

- docs/add-juno-to-an-app/create-a-satellite.md
- docs/build/functions.md
- docs/intro.md
- docs/terminology.md
> docs: subnet and review getting started

- docs/miscellaneous/workarounds.md
> docs: workaround "how to collaborate on the same "project"

- docs/build/functions/development.md
I don't provide a redirect given that the page is literally live only since few hours and has probably no backlink yet.
> docs: rename getting started functions into development

- docs/guides/github-actions.mdx
We can now leverage the `predeploy` option instead.
> docs: remove build from GitHub Actions

- docs/create-a-satellite.mdx
- docs/miscellaneous/best-practices.md
- docs/miscellaneous/controllers.md
- docs/miscellaneous/memory.md
- docs/miscellaneous/provisioning-options.mdx
- docs/miscellaneous/wallet.md
- docs/miscellaneous/workarounds.md
Moving the subnet out of the "Create satellite" page makes it more readable, therefore better for the onboarding, and also makes sense as the same options are available for Orbiter as well.
> feat: reorder misc and integrate provisioning options

- blog/2025-04-10-data-validation-in-juno-best-practices-and-security.md
> Since it only happens after the data is already written, it can lead to unwanted cascading effects. For example: let's say each new user needs to be added to some list. If the user is invalid, we can't add them to the list, but since the hook runs after the data is written, the user will be added to the list before we can reject them. This adds unwanted complexity to your code, forcing the developer to manage multiple on_set_doc hooks in the same function.
This is an unfortunate example as adding a user in a database from a frontend call sounds like a bad practice with security issue. Rephrased to be generic. Also removed the word "cascading" which might lead to think there is some uncontrolled cascade effects.
> While custom endpoints offer great flexibility for building specialized …
> blog: review blog post

- docs/terminology.md
This PR addresses issue #395  by adding an entry for the shorthand "doc" in the terminology documentation.
The term "doc" is frequently used in the codebase and documentation to refer to a "document of the Datastore," but was previously undefined.
This update makes using "doc" explicit and helps clarify its meaning for users and contributors.
> Add "doc" Definition to Terminology Documentation

- src/components/Hero/index.tsx
If user navigates quickly, it's possible that the deferred typed initialization starts when the landing is not displayed.
Long story short, I forgot a clear timeout on destroy. My bad.
> fix: tagname not defined on typed init

- .llms-snapshots/llms-full.txt
- docs/reference/cli.mdx
> docs: development is a reserved keyword / mode for working with the emulator
