docs/add-juno-to-an-app/deploy-your-app.md
docs/add-juno-to-an-app/install-the-sdk-and-initialize-juno.md

This adds CLI install instructions to and clarifies the getting started docs.

docs: clarify getting started

---

package.json
scripts/build.compress.sh

build: gzip js and css

---

docs/miscellaneous/cli.md

docs: juno config

---

src/pages/index.tsx

Edited on phone, excuse the brevity

fix: typo in landing page

---

docs/build/storage.md

docs: filename for fileUpload lower case and dash

---

docs/pricing.md
docs/troubleshooting.md

Init a troubleshooting page with a note about Windows Powershell and SSR.
Resolves #25.

feat: troubleshooting

---

docs/build/datastore.md

https://github.com/buildwithjuno/juno-js/pull/44

docs: delDoc renamed to deleteDoc

---

docs/miscellaneous/cli.md

docs: cli config path

---

docs/build/hosting.md

docs: other dns providers that does not support CNAME for apex domain

---

docs/build/authentication.md
docs/infrastructure/internet-computer.md
docs/miscellaneous/cli.md
src/components/Auth/index.tsx

docs: fix typos

---

docs/infrastructure/internet-computer.md

Fixed a missing "." at the end of the first paragraph. This is my first ever pull request so idk if I've done everything right

Fix typo in <internet-computer>

---

docusaurus.config.ts
src/components/Auth/index.tsx
src/components/Build/index.tsx
src/components/Build/styles.module.scss
src/components/Developer/index.tsx
src/components/Hero/styles.module.scss
src/components/Libs/index.tsx
src/components/Serverless/index.tsx
src/components/Snippet/index.tsx
src/components/Snippet/styles.module.scss
src/css/colors.scss
src/css/docusaurus.scss
src/mixins/_grid.scss
src/pages/index.module.scss
src/pages/index.tsx

Syntax highlighting theme is oneDark, feel free to switch for another (in docusaurus.config.ts).

style: build section & code samples redesign

---

docs/pricing.md

Just reading and experienced the broken link. Still learning about Juno.

Updated broken console link in pricing.md

---

docs/build/authentication.md

docs: internet identity pin authentication disabled per default

---

docusaurus.changelog.plugin.ts
docusaurus.config.ts
docusaurus.showcase.plugin.ts
package-lock.json
package.json
src/components/Changelog/index.tsx
src/components/Release/index.module.scss
src/components/Release/index.tsx
src/pages/changelog/index.module.scss
src/pages/changelog/index.tsx
src/pages/release/index.module.scss
src/pages/release/index.tsx
src/types/github.ts

feat: changelog

---

showcase.json

feat: remove why-internetcomputer from showcase

---

docs/build/datastore.md
docs/build/storage.md

Issue #89 Document List Options 
Updated List Documents in Datastore.md with detailed descriptions of the parameters of ListDocs along with examples using each parameter. 
Updated List Assets in Storage.md with a detailed example usings matchers, paginate and order.

List options

---

docusaurus.config.ts

feat: link YouTube channel in footer

---

docs/build/datastore.md
docs/build/storage.md

Relates to https://github.com/junobuild/juno/issues/665

docs: max memory size

---

package-lock.json
package.json
src/components/Newsletter/index.tsx
src/components/Newsletter/styles.module.scss
src/pages/index.module.scss
src/pages/index.tsx

I hate to have to use Mailchimp and a react hook to integrate this. 
Using Juno to save the emails in the smart contract would have took no time to develop but, the overhead of maintenance each time a newsletter is send or providing the subscribers to unsubscribe and other form would have take too much time.
So let's do that...

feat: integrate a newsletter (with Mailchimp)

---

docusaurus.config.ts
src/pages/newsletter/index.module.scss
src/pages/newsletter/index.tsx

I want to share that we have a newsletter now, so we need a page to share. 🤪

feat: add newsletter page

---

showcase.json

add icpslime to juno showcase.

feat: add icpslime to showcase

---

docs/white-paper/roadmap.mdx

Add some more features I have in mind in the roadmap for a chat I'll have today.

docs: update roadmap with more features for discussion

---

docs/build/datastore.md
docs/build/storage.md

docs: missing filter param in listDocs and listAssets

---

docs/pricing.md

Follow release https://github.com/junobuild/juno/releases/tag/v0.0.37

feat: update pricing 0.4 ICP for additional satellite or orbiter

---

docs/build/datastore.md
docs/build/storage.md

docs: delete filtered documents and assets

---

docs/build/functions.md

docs: on_init, on_post_upgrade and on_delete_filtered

---

docs/guides/local-development.md

docs: little admin server on port 5999 and get ICP

---

docs/guides/github-actions.md

docs: integrate configuration in GitHub actions

---

docs/terminology.md

A bit a more comprehensive description I hope of cycles.

docs: review cycles terminology

---

docs/pricing.md

No update to the price but, review the example, integrate the Pricing Calculator (resolves #233) and update the various ways available to get cycles.

docs: review pricing content

---

docs/faq.md

Mention that the foundation is funding Juno for 2025 in the FAQ

docs: review FAQ DFINITY

---

docs/troubleshooting.md

docs: agent-js polyfill global is not defined

---

docs/build/functions/development.md

docs: serverless maintenance

---

docs/guides/rust.mdx

docs: integrate rust examples

---

docs/faq.md

docs: information about verifying hash before upgrade

---

docs/miscellaneous/best-practices.md
docs/miscellaneous/wallet.md
docs/miscellaneous/workarounds.md

docs: create best practices with CSP

---

docs/build/authentication/customization.md

docs: review II with domains compatibility

---

docs/guides/local-development.md

docs: local development IDs

---

docs/troubleshooting.md

docs: troubleshooting 1 GB heap max

---

docs/guides/rust.mdx

Added `juno upgrade -t s -s ./target/deploy/satellite.wasm.gz` to Rust section https://juno.build/docs/guides/rust#quickstart

Added update Satellite command to rust section

---

.github/workflows/update-subnets.yml

Same as https://github.com/dfinity/oisy-wallet/pull/5979 credits to @AntonioVentilii
Frequency was also bumped in main repo https://github.com/junobuild/juno/pull/1475

feat(devops): increase frequency of CI for subnets

---

package-lock.json
package.json
src/components/Hero/index.tsx
src/components/Hero/styles.module.scss

feat: typed title

---

package-lock.json
package.json
src/components/Hero/index.tsx

Follow-up of #396
On production, js is slow to load, as a result the sentence is incomplete. Therefore we try to use a placeholder.

feat: typed title with placeholder

---

src/components/Hero/index.tsx

Last try to fix glitch follow of #397

fix: typed title glitch

---

docs/guides/angular.mdx

I added a note section in the Angular documentation to highlight Angular-specific considerations when deploying an app.

Improve documentation of deployment of angular based apps.

---

docs/management/monitoring.md

The trigger amount is not the threshold but, the grace limit required cycles + the custom threshold.

docs: replace monitoring threshold with grace period cycles needed

---

docs/build/analytics/development.md

Update for last version of the SDK

docs: analytics sync and async functions

---

docs/reference/plugins.mdx

- Local dev is now the default
- `initOrbiter` is not async
- Feedback from [Discord](https://discord.com/channels/1076791076544847982/1375572698113245204/1375573535904235561)
- Yarn and pnpm

docs: review plugin reference (notably for local dev)

---

docs/guides/ai.md
sidebars.ts

docs: add guide about AI and LLMs.txt
